#!/usr/bin/env python3
"""Generate native Asma-ul Husna seeds from the canonical progress contract."""

from __future__ import annotations

import argparse
import json
import re
import sys
import uuid
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CONTRACT = ROOT / "contracts" / "progress-model" / "v1"
SOURCE = CONTRACT / "asma-ul-husna.json"
REGISTRY = CONTRACT / "builtin-dhikrs.json"

ANDROID = (
    ROOT
    / "awrad-android/app/src/main/java/app/awrad/awrad_dhikrgoalstracker/data/database/AsmaUlHusnaSeed.kt"
)
IOS = ROOT / "awrad-ios/awrad/awrad/Core/AsmaUlHusnaSeed.swift"
API = ROOT / "awrad_api/priv/asma-ul-husna.json"


def quoted(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def load_source() -> dict:
    data = json.loads(SOURCE.read_text(encoding="utf-8"))
    names = data.get("names")
    if data.get("schema_version") != 1 or data.get("category") != "asma_ul_husna":
        raise ValueError("Asma-ul Husna source must use schema version 1 and category asma_ul_husna")
    if not isinstance(names, list) or len(names) != 100:
        raise ValueError("Asma-ul Husna source must contain exactly 100 names including Allah")

    numbers = [item.get("number") for item in names]
    if numbers != list(range(1, 101)):
        raise ValueError("Asma-ul Husna numbers must be ordered from 1 through 100")

    keys: set[str] = set()
    ids: set[str] = set()
    for item in names:
        key = item.get("catalog_key")
        raw_id = item.get("id")
        if not isinstance(key, str) or not key.startswith("asma-ul-husna-"):
            raise ValueError(f"invalid Asma-ul Husna catalog key: {key!r}")
        parsed = uuid.UUID(raw_id)
        if parsed.version != 4 or str(parsed) != raw_id:
            raise ValueError(f"Asma-ul Husna ID must be a lowercase UUIDv4: {raw_id!r}")
        for field in ("arabic", "transliteration", "meaning"):
            if not isinstance(item.get(field), str) or not item[field].strip():
                raise ValueError(f"{key} has an empty {field}")
        if key in keys or raw_id in ids:
            raise ValueError(f"duplicate Asma-ul Husna identity: {key} / {raw_id}")
        keys.add(key)
        ids.add(raw_id)

    return data


def invocation_transliteration(name: str) -> str:
    if name == "Allah":
        return "Ya Allah"
    bare_name = re.sub(r"^(?:Al|Ar|As|Ash|At|Az|Ad|An)-", "", name).lstrip("'")
    return f"Ya {bare_name}"


def invocation_arabic(name: str, arabic: str) -> str:
    if name == "Allah":
        return "يَا ٱللَّٰهُ"
    if name == "Dhul-Jalali wal-Ikram":
        return "يَا ذَا ٱلْجَلَالِ وَٱلْإِكْرَامِ"
    bare_name = re.sub(r"^[ٱا]ل[\u064b-\u065f\u0670]*", "", arabic)
    bare_name = re.sub(
        r"^(.)([\u064b-\u065f\u0670]*)",
        lambda match: match.group(1) + match.group(2).replace("\u0651", ""),
        bare_name,
    )
    return f"يَا {bare_name}"


def render_registry(source: dict) -> str:
    current = json.loads(REGISTRY.read_text(encoding="utf-8"))
    base = [
        item
        for item in current.get("dhikrs", [])
        if not item.get("catalog_key", "").startswith("asma-ul-husna-")
    ]
    generated = [
        {"catalog_key": item["catalog_key"], "id": item["id"], "status": "active"}
        for item in source["names"]
    ]
    return json.dumps(
        {"schema_version": 1, "dhikrs": base + generated},
        ensure_ascii=False,
        indent=2,
    ) + "\n"


def render_android(source: dict) -> str:
    rows = "\n".join(
        "        entry(%s, %s, %s, %s, %s, %s),"
        % tuple(
            quoted(value)
            for value in (
                item["catalog_key"],
                item["id"],
                invocation_transliteration(item["transliteration"]),
                invocation_arabic(item["transliteration"], item["arabic"]),
                item["meaning"],
                item["number"],
            )
        )
        for item in source["names"]
    )
    return f'''// Generated by scripts/generate_asma_ul_husna.py. Do not edit by hand.
@file:Suppress("MaxLineLength")

package app.awrad.awrad_dhikrgoalstracker.data.database

import app.awrad.awrad_dhikrgoalstracker.data.database.entity.DhikrEntity
import app.awrad.awrad_dhikrgoalstracker.data.model.DhikrCategory
import java.util.UUID

object AsmaUlHusnaSeed {{
    data class Entry(
        val identity: BuiltInDhikrIds.Identity,
        val dhikr: DhikrEntity,
    )

    val entries: List<Entry> = listOf(
{rows}
    )

    val identities: List<BuiltInDhikrIds.Identity> = entries.map {{ it.identity }}
    val dhikrs: List<DhikrEntity> = entries.map {{ it.dhikr }}

    private fun entry(
        catalogKey: String,
        id: String,
        transliteration: String,
        arabic: String,
        meaning: String,
        sortOrder: Int,
    ): Entry {{
        val uuid = UUID.fromString(id)
        return Entry(
            identity = BuiltInDhikrIds.Identity(catalogKey = catalogKey, id = uuid),
            dhikr = DhikrEntity(
                id = uuid,
                catalogKey = catalogKey,
                title = transliteration,
                arabic = arabic,
                transliteration = transliteration,
                translation = meaning,
                audioUrl = null,
                audioFileName = null,
                category = DhikrCategory.ASMA_UL_HUSNA,
                audioCountPerPlay = 1,
                sortOrder = sortOrder,
            ),
        )
    }}
}}
'''


def render_ios(source: dict) -> str:
    rows = "\n".join(
        "        entry(%s, %s, %s, %s, %s, %s),"
        % tuple(
            quoted(value)
            for value in (
                item["catalog_key"],
                item["id"],
                invocation_transliteration(item["transliteration"]),
                invocation_arabic(item["transliteration"], item["arabic"]),
                item["meaning"],
                item["number"],
            )
        )
        for item in source["names"]
    )
    return f'''// Generated by scripts/generate_asma_ul_husna.py. Do not edit by hand.

import Foundation

enum AsmaUlHusnaSeed {{
    struct Entry {{
        let identity: BuiltInDhikrRegistry.Entry
        let dhikr: Dhikr
    }}

    static let entries: [Entry] = [
{rows}
    ]

    static let identities = entries.map {{ $0.identity }}
    static let dhikrs = entries.map {{ $0.dhikr }}

    private static func entry(
        _ catalogKey: String,
        _ rawID: String,
        _ transliteration: String,
        _ arabic: String,
        _ meaning: String,
        _ sortOrder: Int
    ) -> Entry {{
        guard let id = UUID(uuidString: rawID) else {{
            preconditionFailure("Invalid built-in Asma-ul Husna UUID: \\(rawID)")
        }}
        return Entry(
            identity: BuiltInDhikrRegistry.Entry(catalogKey: catalogKey, id: id),
            dhikr: Dhikr(
                id: id,
                catalogKey: catalogKey,
                title: transliteration,
                arabic: arabic,
                transliteration: transliteration,
                translation: meaning,
                category: .asmaUlHusna,
                audioCountPerPlay: 1,
                sortOrder: sortOrder
            )
        )
    }}
}}
'''


def render_api(source: dict) -> str:
    rendered = dict(source)
    rendered["variant"] = "invocation"
    rendered["names"] = [
        {
            **item,
            "invocation_arabic": invocation_arabic(item["transliteration"], item["arabic"]),
            "invocation_transliteration": invocation_transliteration(item["transliteration"]),
        }
        for item in source["names"]
    ]
    return json.dumps(rendered, ensure_ascii=False, indent=2) + "\n"


def outputs(source: dict) -> dict[Path, str]:
    return {
        REGISTRY: render_registry(source),
        ANDROID: render_android(source),
        IOS: render_ios(source),
        API: render_api(source),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail when generated files are stale")
    args = parser.parse_args()

    try:
        rendered = outputs(load_source())
    except (OSError, json.JSONDecodeError, ValueError, TypeError, AttributeError) as error:
        print(f"Asma-ul Husna generation failed: {error}", file=sys.stderr)
        return 1

    stale: list[Path] = []
    for path, content in rendered.items():
        if args.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != content:
                stale.append(path)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")

    if stale:
        for path in stale:
            print(f"stale generated Asma-ul Husna file: {path.relative_to(ROOT)}", file=sys.stderr)
        print("run ./scripts/generate_asma_ul_husna.py", file=sys.stderr)
        return 1

    action = "verified" if args.check else "generated"
    print(f"{action} 100 canonical Asma-ul Husna entries")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
